import Navbar from "@/components/Navbar";
import "./globals.css";
import { Quicksand } from "next/font/google";
import Footer from "@/components/Footer";
import { ReduxProvider } from "@/redux/provider";

const font = Quicksand({
  subsets: ["latin"],
});

export const metadata = {
  title: "Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ReduxProvider>
          <Navbar />
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
